version: '3'
services:
        app:
                build: .
                restart: unless-stopped
                networks:
                        - mongo_network
                environment:
                        MONGODB_HOSTNAME: MONGODB_HOSTNAME
                        MONGODB_DATABASE: MONGODB_DATABASE
                        MONGODB_USERNAME: MONGODB_USERNAME
                        MONGODB_PASSWORD: MONGODB_PASSWORD
                depends_on:
                        - mongo
        mongo:
                image: mongo

                restart: unless-stopped
                environment:
                        MONGO_INITDB_ROOT_USERNAME: MONGO_INITDB_ROOT_USERNAME
                        MONGO_INITDB_ROOT_PASSWORD: MONGO_INITDB_ROOT_PASSWORD
                        MONGO_INITDB_DATABASE: MONGO_INITDB_DATABASE
                        MONGODB_DATA_DIR: /data/db
                        MONGODB_LOG_DIR: /dev/null

                volumes:
                        - mongo_data:/data/db
                networks:
                        - mongo_network
        mongo-express:
                image: mongo-express
                restart: always
                ports:
                        - 8081:8081
                environment:
                        ME_CONFIG_MONGODB_ADMINUSERNAME: ME_CONFIG_MONGODB_ADMINUSERNAME
                        ME_CONFIG_MONGODB_ADMINPASSWORD: ME_CONFIG_MONGODB_ADMINPASSWORD
                        ME_CONFIG_MONGODB_SERVER: ME_CONFIG_MONGODB_SERVER
                networks:
                        - mongo_network
                depends_on:
                        - mongo
networks:
        mongo_network:
                driver: bridge

volumes:
        mongo_data:
                driver: local
